package com.rafael.hibernet.Modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

// Generated 1 jun. 2020 15:00:16 by Hibernate Tools 5.4.14.Final

/**
 * Curso generated by hbm2java
 */
@Data
@Entity
@Table(name="curso")
public class Curso implements java.io.Serializable {

	@Id
	@Column(name="idCurso")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idCurso;
	@Column(name="nombre")
	private String nombre;
	@Column(name="docente")
	private String docente;
	@Column(name="lugar")
	private String lugar;
	

	public Curso() {
	}

}
