package com.rafael.hibernet.Modelo;
// Generated 1 jun. 2020 15:00:16 by Hibernate Tools 5.4.14.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * TbAlumno generated by hbm2java
 */
@Data
@Entity
@Table(name="tbAlumno")
public class TbAlumno implements java.io.Serializable {
	
	@Id
	@Column(name="idtbAlumno")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer idtbAlumno;
	
	@Column(name="nombre")
	private String nombre;
	
	@Column(name="apellido")
	private String apellido;
	
	@Column(name="edad")
	private Integer edad;


}
