package com.rafael.hibernet.Modelo;
// Generated 1 jun. 2020 15:00:16 by Hibernate Tools 5.4.14.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * TdAdministrativo generated by hbm2java
 */
@Data
@Entity
@Table(name="tdAdministrativo")
public class TdAdministrativo implements java.io.Serializable {

	@Id
	@Column(name="codEmp")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer codEmp;
	
	@Column(name="nomEmp")
	private String nomEmp;
	
	@Column(name="apeEmp")
	private String apeEmp;
	
	@Column(name="loginEmp")
	private String loginEmp;
	
	@Column(name="claveEmp")
	private String claveEmp;

	public TdAdministrativo() {
	}

}
